cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    bertuci:
      email: mateusbertuci@hotmail.com
      name: Matheus Henrique Bertuci
      password: $2b$12$w53y7m8Qtef42tC/d.JIoOlRHJsHgMzp/Hj.Gk0ve1uQVk4DGYHV.
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: 123
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: 456
    teste:
      email: teste@hotmail.com
      name: testa
      password: $2b$12$irxKJa19lZG0Xhi5eqin4u2RVzUaxPXLW9Ovuw6ax72DkrqroO3mC
preauthorized:
  emails:
  - melsby@gmail.com
